### ISSUE TITLE
江湖救急-java.net.ConnectException: failed 开启vpn后连接超时。

### ISSUE THREAD

**Issue by dodan100** [dawei101/shadowsocks-android-java#64]
打开VPN之后一直报超时，可以是其他的Vpn软件就能正常上。不知道啥情况了。帮忙看下以下错误？？？谢谢大神。

.shadowsocks W/System.err: java.net.ConnectException: failed to connect to /121.51.140.141 (port 8080): connect failed: ENETUNREACH (Network is unreachable)
01-18 16:00:12.226 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:124)
01-18 16:00:12.226 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:110)
01-18 16:00:12.226 14256-14695/com.vm.shadowsocks W/System.err:     at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:199)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at java.lang.Thread.run(Thread.java:833)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err: Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.Posix.connect(Native Method)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
01-18 16:00:12.227 14256-14695/com.vm.shadowsocks W/System.err: 	... 6 more

**Comment by dawei101** [comment]
Network is unreachable

2018-01-18 16:05 GMT+08:00 dodan200 <notifications@github.com>:
