### ISSUE TITLE
问题如下：

### ISSUE THREAD

**Issue by quguangle** [dawei101/shadowsocks-android-java#76]
java.io.IOException: Connection reset by peer
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at sun.nio.ch.IOUtil.read(IOUtil.java:197)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at com.vm.shadowsocks.tunnel.Tunnel.onReadable(Tunnel.java:125)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:71)
05-24 09:29:40.434 10723-11103/com.vm.shadowsocks W/System.err:     at java.lang.Thread.run(Thread.java:760)

请问这是什么原因造成的，能给一下解决思路码？丢包率很严重。希望作者能一直延续的维持这个库

**Comment by quguangle** [comment]
将次功能做的更加完善
