### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by justyu** [dawei101/shadowsocks-android-java#78]

**Comment by justyu** [comment]
update logs:

I/System.out: [21:55:15] Global mode is off
I/System.out: [21:55:15] Proxy All Apps
I/System.out: [21:55:15] shadowsocks已连接
I/Toast: Show toast from OpPackageName:com.vm.shadowsocks, PackageName:com.vm.shadowsocks
V/RenderScript: 0x9f417000 Launching thread(s), CPUs 4
W/System.err: java.nio.channels.UnresolvedAddressException
                  at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
                  at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
                  at java.lang.Thread.run(Thread.java:818)
I/System.out: No host name found: 111.202.16.202[21:55:46] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException
W/System.err: java.nio.channels.UnresolvedAddressException
                  at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
                  at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
                  at java.lang.Thread.run(Thread.java:818)
I/System.out: [21:55:47] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException
W/System.err: java.nio.channels.UnresolvedAddressException
                  at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
                  at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
                  at java.lang.Thread.run(Thread.java:818)
I/System.out: [21:55:47] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException
W/System.err: java.nio.channels.UnresolvedAddressException
                  at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
                  at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
                  at java.lang.Thread.run(Thread.java:818)
I/System.out: [21:55:53] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException
W/System.err: java.nio.channels.UnresolvedAddressException
W/System.err:     at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
                  at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
I/System.out: [21:55:54] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException
W/System.err: java.nio.channels.UnresolvedAddressException
                  at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:453)
                  at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:180)
                  at com.vm.shadowsocks.tunnel.Tunnel.connect(Tunnel.java:61)
W/System.err:     at com.vm.shadowsocks.core.TcpProxyServer.onAccepted(TcpProxyServer.java:120)
                  at com.vm.shadowsocks.core.TcpProxyServer.run(TcpProxyServer.java:77)
                  at java.lang.Thread.run(Thread.java:818)
I/System.out: [21:55:54] Error: remote socket create failed: java.nio.channels.UnresolvedAddressException

**Comment by justyu** [comment]
@dawei101   any idea?
